###############################################################################
#
#   Requirements of the package.
#
#   AUTHOR: {{cookiecutter.author}}
#   AFFILIATION: {{cookiecutter.affiliation}}
#   CONTACT: {{cookiecutter.contact}}
#   CREATED: {{cookiecutter.date_created}}
#   LICENSE: {{cookiecutter.license}}
#
###############################################################################
---

channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - pytest=5.1.2

...