###############################################################################
#
#   Config file for this Snakemake pipeline.
#
#   AUTHOR: {{cookiecutter.author}}
#   AFFILIATION: {{cookiecutter.affiliation}}
#   CONTACT: {{cookiecutter.contact}}
#   CREATED: {{cookiecutter.date_created}}
#   LICENSE: {{cookiecutter.license}}
#
###############################################################################
---

# path to the directory with all the scripts and executable files
src_dir: "src"

# path for the result directory
output_dir: "output_dir"

# file names for the random samples
samples_filenames:
  - "sample1"
  - "sample2"
  - "sample3"
  - "sample4"
  - "sample5"

...
