###############################################################################
#
#   Config file for this Snakemake pipeline.
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 23-09-2019
#   LICENSE: GPL
#
###############################################################################
---

# path to the directory with all the scripts and executable files
src_dir: "scripts"

# path for the result directory
output_dir: "output_dir"

# file names for the random samples
LSM_windows_files:
  - "sample1"
  - "sample2"
  - "sample3"
  - "sample4"
  - "sample5"

...
